name: capstonedesign_flutter
description: "A Flutter app for CapstoneDesign to analyze emotions and provide daily reflection feedback."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  provider: ^6.1.2  # 상태 관리 추가
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mobilenetv2.tflite  # TFLite 모델 추가